"use strict";

module.exports = Object.freeze([
    "storage/schema.js",
    "storage/connection.js",
    "storage/upgrade.js",
    "storage/read.js",
    "storage/write.js",
    "storage/pure/persistence-records.js",
    "storage/lifecycle-persistence.js",
    "storage/successful-cycle-persistence.js",
    "storage/recorder-diagnostics-persistence.js",
    "messaging/pure/channel-message-logic.js",
    "messaging/channel.js",
    "recorder/pure/config-logic.js",
    "recorder/pure/universe-logic.js",
    "recorder/pure/securities-chunk-logic.js",
    "recorder/pure/cycle-logic.js",
    "recorder/pure/recorder-loop-logic.js",
    "recorder/pure/diagnostics-logic.js",
    "recorder/config.js",
    "recorder/diagnostics.js",
    "recorder/universe-loader.js",
    "recorder/securities-chunk-fetcher.js",
    "recorder/cycle-builder.js",
    "recorder/recorder-loop.js",
    "viewer/pure/viewer-state.js",
    "viewer/pure/current-table-logic.js",
    "viewer/pure/diagnostics-logic.js",
    "viewer/current-table.js",
    "viewer/history-data.js",
    "viewer/security-detail.js",
    "viewer/diagnostics-data.js",
    "viewer/diagnostics.js",
    "viewer/live-refresh.js",
    "viewer/bootstrap.js"
]);
